### ISSUE TITLE
Camera position demo misplaces camera in some cases

### ISSUE THREAD

**Issue by Zwatotem** [software-mansion-labs/expo-maps#62]
Environment: iOS 15.4; iPod touch 7th gen.
Expected behaviour: Camera center is placed at the selected feature.
Actual behaviour: Top-left corner of the camera is placed at the selected feature.
Steps to reproduce: 
1. Open exaple app
2. Go to "Camera Position" section.
3. If the behaviour is correct go back and reenter.
4. Repeat step 3. Incorrect behaviour seems to appear randomly.

**Comment by szdziedzic** [comment]
Overall this `camera position` prop malfunctions right now, because once we change any prop in `Map` component, camera gets moved to the position specified in prop again.
